### ISSUE TITLE
Note on your readme

### ISSUE THREAD

**Issue by LindaLawton** [unidevel-com/unidevel-openweather#1]
Would be nice to see an example for how to add the key to dependency injection and adding the key directly to the calls.   Took me 10 minutes to figure out why the code you had given hadn't worked.   I had missed the API key section completely.

Nice library Im using it in a talk i am giving next month thanks :)

**Comment by gstr-unidevel** [comment]
Hi Linda, you're right. I'll try to update readme.md this week. It'll be easier to use this library if you could start with simple copy-paste scenario.

**Comment by gstr-unidevel** [comment]
@LindaLawton I've updated readme.md, I think detailed information how to use DI is out of scope for this project, but I have included simple information how to create and provide basic IConfiguration with api key.
